package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDefaultValid(t *testing.T) {
	if err := Default().Validate(); err != nil {
		t.Fatal(err)
	}
}

func TestDefaultListensOnAllInterfaces(t *testing.T) {
	if got := Default().Listen; got != "0.0.0.0:8989" {
		t.Fatalf("Listen=%q, want 0.0.0.0:8989", got)
	}
}

func TestDefaultAdminUsernameNotPassword(t *testing.T) {
	cfg := Default()
	if cfg.AdminUsername != "admin" {
		t.Fatalf("AdminUsername=%q, want admin", cfg.AdminUsername)
	}
	if cfg.AdminPassword != "" {
		t.Fatalf("AdminPassword=%q, want empty (generated by Load, not a fixed default)", cfg.AdminPassword)
	}
}

func TestValidateRejectsBlankAdminUsername(t *testing.T) {
	cfg := Default()
	cfg.AdminUsername = ""
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected error for blank admin_username")
	}
}

func TestValidateAllowsBlankAdminPassword(t *testing.T) {
	// Blank is the legitimate "generate one" sentinel prior to Load()
	// resolving it — Validate() alone must not reject it.
	if err := Default().Validate(); err != nil {
		t.Fatal(err)
	}
}

func TestLoadGeneratesAndPersistsAdminPassword(t *testing.T) {
	t.Setenv("STATE_DIRECTORY", t.TempDir())
	t.Setenv("CHIMERA_ADMIN_PASSWORD", "")

	cfg1, err := Load("")
	if err != nil {
		t.Fatal(err)
	}
	if cfg1.AdminPassword == "" {
		t.Fatal("expected a generated admin password")
	}
	if cfg1.AdminPasswordFile == "" {
		t.Fatal("expected AdminPasswordFile to be set for a generated password")
	}
	if _, err := os.Stat(cfg1.AdminPasswordFile); err != nil {
		t.Fatalf("password file not written: %v", err)
	}

	// A second Load must reuse the persisted password, not rotate it.
	cfg2, err := Load("")
	if err != nil {
		t.Fatal(err)
	}
	if cfg2.AdminPassword != cfg1.AdminPassword {
		t.Fatalf("password changed across Load() calls: %q != %q", cfg1.AdminPassword, cfg2.AdminPassword)
	}
}

func TestLoadUsesExplicitAdminPasswordOverGeneration(t *testing.T) {
	t.Setenv("STATE_DIRECTORY", t.TempDir())
	t.Setenv("CHIMERA_ADMIN_PASSWORD", "operator-set-password")

	cfg, err := Load("")
	if err != nil {
		t.Fatal(err)
	}
	if cfg.AdminPassword != "operator-set-password" {
		t.Fatalf("AdminPassword=%q, want the explicitly configured value", cfg.AdminPassword)
	}
	if cfg.AdminPasswordFile != "" {
		t.Fatalf("AdminPasswordFile=%q, want empty when the password was explicitly configured", cfg.AdminPasswordFile)
	}
	if _, err := os.Stat(filepath.Join(os.Getenv("STATE_DIRECTORY"), "admin-password")); err == nil {
		t.Fatal("no password file should be written when the password was explicitly configured")
	}
}
